backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "catalogs"
    label: "Catalogs"
    folder: "catalogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Price (PKR)", name: "price_pkr", widget: "number" }
      - { label: "Price (USD)", name: "price_usd", widget: "number"}
